// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkjw-otAkTT4HesmnyxevJRqsWpSqUS_4',
    appId: '1:646569955046:web:395958792b030e0a787527',
    messagingSenderId: '646569955046',
    projectId: 'dash-32734',
    authDomain: 'dash-32734.firebaseapp.com',
    storageBucket: 'dash-32734.appspot.com',
    measurementId: 'G-L057RYKVZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpm8ork8nBMVp4q-uDuljQQTiplaJUrak',
    appId: '1:646569955046:android:69ba55ec7dce7eea787527',
    messagingSenderId: '646569955046',
    projectId: 'dash-32734',
    storageBucket: 'dash-32734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1qvKqV71s7j7wCKY3fXV7Vur1VYqyFg',
    appId: '1:646569955046:ios:546c88aa4d79d95f787527',
    messagingSenderId: '646569955046',
    projectId: 'dash-32734',
    storageBucket: 'dash-32734.appspot.com',
    iosBundleId: 'com.example.dashEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1qvKqV71s7j7wCKY3fXV7Vur1VYqyFg',
    appId: '1:646569955046:ios:7145fa31c2a2c83d787527',
    messagingSenderId: '646569955046',
    projectId: 'dash-32734',
    storageBucket: 'dash-32734.appspot.com',
    iosBundleId: 'com.example.dashEvent.RunnerTests',
  );
}
